name: Angular CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build -- --configuration production

    - name: Deploy to IIS
      shell: powershell
      run: |
        $destination = "C:\inetpub\wwwroot\Angular online-sales"

        if (!(Test-Path $destination)) {
          New-Item -ItemType Directory -Force -Path $destination
        }

        Remove-Item "$destination\*" -Recurse -Force -ErrorAction SilentlyContinue
        Copy-Item "dist\online-sales\browser\*" $destination -Recurse -Force